[book]
title = "My Awesome Book"
author = "Abhinandh S"
description = "This is a detailed description of the book."
language = "en"

# Optional settings for customization
# theme = "light"  # "dark" for dark theme or "light" for light theme

