keys:
  - &users:
    - &abhi age1hrun3cvctc7whpnpmvspxsdej47wmwc7nz5zcut0rxlu6nksqyhsegg4u4
  - &hosts:
    - &abhi-mobile age1n7jsgfl9sj0whn6kehyplkjfc9qctga08yc6ajhae68rp4nm03gq4m96fg
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *abhi
        - *abhi-mobile
